# Generated by Django 5.0.7 on 2024-10-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='edit_approved',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='edit_requested',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
